### ISSUE TITLE
Create search feature

### ISSUE THREAD

**Issue by bhokin** [Jakarin-Jojo/ThaiMoung#28]

**Comment by XOQDY** [comment]
When I do this feature I recommend we should separate nav-bar code to nav-bar.html this eliminates the need to modify the code multiple times because I need to edit code in nav-bar part so I decide to move it and in the nav-bar code section I use include instead of code. 😎

**Comment by XOQDY** [comment]
Oh!!!!, I almost forgot: when people search, do you want it to display on the website what the user is currently searching for?
@Jakarin-Jojo

**Comment by Jakarin-Jojo** [comment]
> When I do this feature I recommend we should separate nav-bar code to nav-bar.html this eliminates the need to modify the code multiple times because I need to edit code in nav-bar part so I decide to move it and in the nav-bar code section I use include instead of code. 😎

That's a great idea.
