### ISSUE TITLE
Write a Iteration 1 plan

### ISSUE THREAD

**Issue by Jakarin-Jojo** [Jakarin-Jojo/ThaiMoung#4]
Create a page **Iteration 1** plan and write an **Iteration 1 plan**.

**Comment by XOQDY** [comment]
I change template about Taskboard

**Comment by XOQDY** [comment]
In feature I add:
- Have an CI/CD in project.
In acceptance criteria :
- The CI and Coverage "badges" in Gtihub README.md work as valid links.

**Comment by XOQDY** [comment]
My iteration 1 plan ideas have sold out. If no one else has anything to add, I'm confident we can close this issue.

**Comment by NamoSmith** [comment]
Nice work!
